### ISSUE TITLE
Plain text has no stable position on the screen

### ISSUE THREAD

**Issue by smsti** [wout/svg.js#248]
Hello Wout,

I have a plain text inside a group, which uses scale. When I change coordinates of the text, the text sometimes slightly changes its position. That is expected. But the new coordinates have the same values as the old ones. If I change the coordinates in such way, that the new ones are the same as old ones, the text should not move.

I failed to make fiddle. But when I tried to make the fiddle I have noticed that "Inspect element" indeed shows that the coordinate changes for no obvious reason. I do not know whether this fiddle is the same thing as my problem, perhaps: http://fiddle.jshell.net/3pfarcwu/3/

But the big issue now is that I have just observed that svg.js is whole dead under IE 11/Win 8.1. Nothing works there: neither your website nor my very simple attempts. I do not consider any library useful if it fails under widely spread browser. Could you response on this?

**Comment by Fuzzyma** [comment]
As wout already mentioned: Your fiddle is NOT working.
I finally fixed it -> http://fiddle.jshell.net/3pfarcwu/4/
Still - I dont get your problem

**Comment by smsti** [comment]
Hello Fuzzyma, thank you for response.

If you check x, y attributes of the text element in the fiddle, you will find out that those values change for no obvious reason. At least I can observe in both Chrome and IE 11. Watch the <text> element itself within the DOM tree while clicking on it to enforce move() to the same position.

**Comment by Fuzzyma** [comment]
Did you mean the changes  at 

    118.68779167598069
             ^---- this

position?
Roundingerrors! And you wont notice them. Browser doesnt support micro-pixel.
Plus: I tried the fiddle in Chrome and here the text is not visually moving, too.

**Comment by smsti** [comment]
Yes, that's it.

I observed in my app that text is jumping for no obvious reason when moved from its place to the same place. And from user's perspective it was quite annoying. My app is too complicated to make a simple fiddle from that. But when I tried to make fiddle, I did observe the behavior described above.

I do not claim the text in fiddle is moving. But the coordinate is changing so in other configuration it might be moving. SVG also does support scale so that "rounding error" can be multiplied.

**Comment by Fuzzyma** [comment]
First of all do: Round your numbers. You shouldnt wonder about rounding errors when you calculate c-coords like 211.12345236332.

This will prevent your issue in many cases.
I notices that it is still there when 0px are calculated for the y-coord.
That comes with the nature of floats. The Browser calculates the BBox as exactly as he can. The text is positioned taking this BBox-value into account. When you place it again at exactly the same spot (0px) the float is more exactly since the number itself is not like 100px but nearly zero. Thats why the float is something like 1.52241252e-7 and thats why the coords chance again and again.

There is nothing we can do about it except rounding BBox-values but thats something I want to prevent.
The Error is in the micro-px-area which means unless you wont scale your text with 100000 it wont be noticed
