### ISSUE TITLE
Free transform for SVG.js

### ISSUE THREAD

**Issue by pawciow88** [wout/svg.js#254]
Is there any extension/plugin or easy way of creating free transform functionality for svg.js elements?
Other frameworks (snap, raphael) has them (like here https://github.com/ElbertF/Raphael.FreeTransform), 
but I can't find it for svgjs.

I found svgjs best of them - had no issues so far with nesting elements, which is required for my project, but I really miss that functionality.

**Comment by Fuzzyma** [comment]
@pawciow88 - I wrote svg.select.js which seems to solve your problem completely.
I dont know if this still relevant but I really would like to know what you are missing on the plugin.
Give me a chance to approve it :)

**Comment by pjfsilva** [comment]
@Fuzzyma I am also interested in having a free transform tool for SVG.js but I fail to understand exactly how svg.select.js achieves this? 

Actually, what does svg.select.js do? Because from my small demo of it and understanding the code it seems it just adds some visual UI to a selected element but there is no handling of rotating/changing size of the element when the buttons are pressed/dragged.

Is there any way to integrate it with svg.draw.js or something else I'm missing to use these plugins and get a free transform tool like "Raphael.FreeTransform"?

**Comment by Fuzzyma** [comment]
Take a look at http://github.com/fuzzyma/svg.resize.js which is exactly what you are looking for. 
I divided this 2 plug-ins to keep things clean. 
With svg.resize.js resizing and rotation is implemented. 
However I never tested it for path.
