### ISSUE TITLE
Animating a polyline mask not working in Firefox

### ISSUE THREAD

**Issue by ceri-richmond** [wout/svg.js#287]
Loving svg.js - however - it seems a polyline mask will not animate in Firefox (v.33.1.1)

Here's a fiddle, works good in latest release browsers (Chrome / IE / Safari), all except FF:

http://jsfiddle.net/g1bymekq/3/

Any ideas?

Rgds,
Ceri

**Comment by Nephelococcygia** [comment]
If you use polygon instead of polyline, it's gonna work.

**Comment by ceri-richmond** [comment]
Erm, no it doesn't, check the fiddle. I tried adjusting to polygon, same result, doesn't work in FF.

**Comment by Fuzzyma** [comment]
I tried to fix that but Firefox is a bitch. Since a mask is not rly visible on the screen, FF wont give you a bbox for it.
You can try the following:
Create the content of the mask and duplicate it into the visible svg (you can hide it with `visibility:hidden`).
Now you can Animate the visible element and bind an AttributeObserver to it.
This way you can update the mask accordingly.

Or you just use Chrome^^

**Comment by Fuzzyma** [comment]
I figured out a workaround. A bit ugly but it works.
