### ISSUE TITLE
Integration with AngularJS

### ISSUE THREAD

**Issue by gavia** [wout/svg.js#315]
I'm trying to get this to work with AngularJS (loaded by RequireJS) and I'm running into an issue where when I load svg.js, AngularJS essentially breaks (specifically 'angular.module is not a function').

Does anyone know if there's a way to make this work, or am I wasting my time?

**Comment by jbielick** [comment]
I'd guess you're not exporting angular.js module correctly when `require`ing it. If you require angular and try `angular.module(` and it says `module` is not a function, that means `angular` variable is probably just an empty object that require gave you because the actual angular module wasn't exported in the actual angular.js file.

**Comment by Fuzzyma** [comment]
@gavia - is @jbielick right here and this can be closed?

**Comment by gavia** [comment]
I don't think this was the solution, but I gave up a while ago and decided to use another library, so yes this can be closed.

For documentations sake, the break only happened when using this library in particular. I never got this error with any other libraries.

**Comment by RoestVrijStaal** [comment]
@gavia Which "another" library did you use?
