### ISSUE TITLE
Text.clone() wraps text in <tspan>s

### ISSUE THREAD

**Issue by maix** [wout/svg.js#324]
Cloning a Text node created using `plain()` (and thus having the form `<text>myText</text>`) results in the clone being of the form `<text><tspan dy="...">myText</tspan></text>`.

[Example fiddle](http://jsfiddle.net/0109r3y3/)

I know this can be somehow avoided when using `text.move()` of `group.translate()` instead, but this breaks the spirit of svg, and I need to move the whole group, not single elements.  Plus, I think that cloning should, well, clone :)

**Comment by Fuzzyma** [comment]
I am with you. Cloning should just clone.
The bug occurs because the clone-method calls `text()` instead of `plain()` which then leads to a `tspan` in your text (as first line).

For now you can just go with the fix `g2.add(t1.clone().move(0,0))` which moves the text back to its position. I will fix that later.

**Comment by maix** [comment]
> For now you can just go with the fix …
Thanks.

I think the core problem is that text.content is used. If there was one `tspan` with x attribute that is not zero, has a `class` set, ..., all that would just get lost (I assume. Not tested).  I think it should instead just recursivly clone all the `tspan` nodes.

**Comment by Fuzzyma** [comment]
Yes, cloning relies on the `text.content`-property which is not properly updated when e.g. using a function. Thats why cloning fails there.
svg.js has no deep-clone till now. Elements which are cloned are just recreated which leads to the problem with text since text is based on child-elements, too.
Basically it would just be needed to clone all children (including text-nodes), yes - still there is the problem with nested tspans... and so on...

**Comment by Fuzzyma** [comment]
this bug is solved in svg.js v2
