### ISSUE TITLE
drawing.clear() does not remove the defs

### ISSUE THREAD

**Issue by ctzurcanu** [wout/svg.js#325]
If it does not have the intention of removing all children, we need another function that does.

**Comment by Fuzzyma** [comment]
In which case you are forced to remove the defs?

**Comment by ctzurcanu** [comment]
Thank you for such a fast answer. I would like to repeatedly set var mySvg = SVG('id') and destroy the var for programatic reasons. At each creation it adds defs but at each destruction I cannot remove them :(

**Comment by Fuzzyma** [comment]
If you destroy the whole school you should call drawing.remove() to remove the svg root element  from the dom. When you now reinitialize the svg it is clean and new. 

If this is not what you want you can call drawing.defs().remove but this will render the instance useless because many features relay on the defs - property. (actually I didn't test it in the whole). However if you reinitialize the whole svg then this should work, too

**Comment by ctzurcanu** [comment]
i tried .defs.remove() and it has bad side effects. on the other hand I don't want to destroy the svg element. would have been nice if mySvg = SVG('id') would not add a new def if an empty one exists ..

**Comment by Fuzzyma** [comment]
You clear the whole svg and even destroy the reference and you don't want to remove the svg - root? That makes no sense to me. 

Anyway - you can try the second version of svg.js which comes with an adopt-function. Maybe you can use it to adapt the svg again and again. But note that version 2 is still under development

**Comment by ctzurcanu** [comment]
an adopt function seems to be exactly what my intent is. thanks.

**Comment by Fuzzyma** [comment]
Btw: There is a plugin for version 1: https://github.com/wout/svg.absorb.js
