### ISSUE TITLE
SVGText Element.y() , why does it subtract bbox.y from it ?

### ISSUE THREAD

**Issue by saadfaisal** [wout/svg.js#334]
I am trying to recreate a saved design , and when saving i get the transform nodes of the element ( x, y) and use them to recreate the element when the user wants to load an existing design.

However , the y coordinate of the element looses some pixel height and upon investigation i found that its because of the following code 

    , y: function(y) {
        var oy = this.attr('y')
          , o  = typeof oy === 'number' ? oy - this.bbox().y : 0
  
        /* act as getter */
        if (y == null)
          return typeof oy === 'number' ? oy - o : oy
  
        return this.attr('y', typeof y === 'number' ? y + o : y)
      }

I am really trying to understand , why a similar thing is not followed in x() function and what exactly is the need to subtract the "this.bbox().y" from "oy" , and once subtract another difference when the function is called as a getter

        if (y == null)
          return typeof oy === 'number' ? oy - o : oy

Can anyone explain , this looses my ability to recreate the exact design , how should i go about it ??

**Comment by Fuzzyma** [comment]
I admit that I do not fully understand that part of the code.
It seems to calculate the difference between the y-value and the actual y-value of the bbox which should be the same in my opinion.
Maybe it has something to do with how svg places text according to its y-value.
When you place a text at y=0 its actually not where you think it is because the reference-Point is not the upperleft corner of the text. Thats what svg.js corrects here.
Svg.js has logic to handle lines which influence this magic here, too.

**Comment by saadfaisal** [comment]
but the real issuse here is when i attempt to save the element's x() and y() values , and then attempt to recreate them using the move( previously_saved_x , previously_saved_y) , the text element doesnt get placed specifically on the same y location , however x location is fine. Any ideas how to resolve this ?

**Comment by Fuzzyma** [comment]
You can set the y-Attribute using `element.attr()` which does no further calculation while setting the attribute. But make sure you set the `dy`-value accordingly, too
