### ISSUE TITLE
How to set metadata tag?

### ISSUE THREAD

**Issue by agladysh** [wout/svg.js#349]
I need to provide metainformation for my SVG image via `<metadata>` tag. How do I do this with svg.js?

http://www.w3.org/TR/SVG/metadata.html

**Comment by Fuzzyma** [comment]
The children of a metadata-tag are in a different namespae which svg.js wont handle.
You can try to invent your own element using SVG.invent

    SVG.Meta = SVG.invent({
        // Initialize node
      create: 'metadata'
        // Inherit from
    , inherit: SVG.Parent
        // Add parent method
    , construct: {
        // Create a meta element
        meta: function() {
          return this.put(new SVG.Meta())
        }
      }
      
    , extend: {
        addTag: function(node, ns, attr){
            var element = document.createElementNS(ns, node)
            for(var a in attr){
            
                var at = document.createAttributeNS(a.url, [a.ns a.attr].join(':'));
                at.nodeValue = a.value;
                element.setAttributeNodeNS(at);
            
            }
           
            this.add(element)
        
        }
      }
    })

That wont work since its just a try. You have to think about that on your own. I think svg gives you the possibility to do that.
Maybe in later versions that will be implemented but for now I have to disappoint you.

If you come up with a solution feel free to post it here!
