### ISSUE TITLE
Multiline text did not wrap properly to tspans

### ISSUE THREAD

**Issue by ch3sn3k** [wout/svg.js#362]
I have text node in embedded SVG created by different tool than svg.js. I adopt the TEXT node using `SVG.adopt` function. Than I want to set new text to the TEXT element. 

The problem is that the first line of the new text receives `dy` attribute, so the text did not start at the beginning. See fiddle here>

http://jsfiddle.net/wxbfqzot/4/

**Comment by Fuzzyma** [comment]
The dy-attribute is always added. Instead the y-position of the text-element itself is changed to get to the "zero-point" again. That makes handling with all lines easier (you just have to add the same dy to every tspan). To rearrange your text just call `text.text('Hello\nWorld!').y(0)` on your fiddle.

**Comment by ch3sn3k** [comment]
Ok this fixis my example in fiddle. The issue is that when I place text element in the canvas using `x` and `y` attributes I can't call `text.y(0)` since I change the position. Currently I am using
`text.text('Hello\nWorld!').lines().get(0).attr('dy',0)`

**Comment by Fuzzyma** [comment]
When you change the position of your text, svg.js adjusts your call to `text.y()` accordingly so that the first line is at the right position. There is no need to place the first line manually at that spot.

When you want to place the text at the position it was before import you can use

    text.y(text.attr('y'));

Which places the text at the position you want
