### ISSUE TITLE
create a new SVG.Doc wihout attaching it to the DOM.

### ISSUE THREAD

**Issue by theadedmonkey** [wout/svg.js#382]
Is there a way to create an instance of a SVG document without actually attaching it to the body tag or to a DOM element with an id, i say, how can i do something like this.

```
var draw = SVG(); // dont want to render the node when its created
var circle = draw.circle(50); // dont want to render the node when its created
$('#draw').append(draw.node);
```

**Comment by Fuzzyma** [comment]
SVG uses a second SVG-Element as a parser which has to be placed in the dom to work. Thats why it is not intended to _not_ include the root SVG in the doc.
Furthermore all elements are getting created in the dom immeditately so you cant create them later because the information are getting lost (said that, you would have to flush the whole svg-doc at once into the dom, which is just not implemented)
