### ISSUE TITLE
Drastic performance hit on master

### ISSUE THREAD

**Issue by agladysh** [wout/svg.js#391]
In my small script the master is several orders of magnitude slower than v2.1.1.

I can provide additional diagnostics if there are no breaking changes that could do that and that I missed.

**Comment by Fuzzyma** [comment]
I could only think about the bbox change as a change which would hit the performance (8617a6b5d5ff147718051a7fc582c54f603aa90f). But this change is only applied in very edge cases and should not effect the normal flow (and even only in FF).

I would be very thankfull if you could track that down. Maybe you test commit by commit?
Note that some commits there are not stable because I missed to add a file - well - you will see it.

**Comment by agladysh** [comment]
I saw lots of bbox-related stuff in the profiler. Let me reproduce it...

**Comment by agladysh** [comment]
Meanwhile, you can try the script for yourself: https://gist.github.com/agladysh/df5d17ad7a0141a63e74

You can comment out `update()` call on line 943 to prevent it from hanging right away. Press Update button to render when you are ready.

**Comment by agladysh** [comment]
Ugh. Now my profiler crashes :( Anyway, tell me if you want me to `git bisect` svg.js on my side. I should be able to do that this week.

**Comment by Fuzzyma** [comment]
To check for the bbox calls just insert a console.log into the new added try-catch-blog (commit above).

Do you deal with lots of elements in the defs when calling bbox?

Since I am busy with the textmorphing feature I have no time to investigate that further.
If you find the time a git bisect would be really cool!

**Comment by Fuzzyma** [comment]
Check out the latest commit which maybe fix this performance issues (0b5b0eb4842c0bad045a69981d00cba7010f8d31)

**Comment by agladysh** [comment]
Fix worked, thanks!
