### ISSUE TITLE
Event/screen coordinates -> internal coordinates

### ISSUE THREAD

**Issue by edemaine** [wout/svg.js#403]
1. I'd like to suggest that every node object (in particular root SVG objects) have a method for converting given screen coordinates to the coordinate system of the node.  Currently this can be done with the following code:

  ```
  function transformPoint(screenX, screenY) {
    var p = this.node.createSVGPoint()
    p.x = screenX
    p.y = screenY
    return p.matrixTransform(this.node.getScreenCTM().inverse())
  }
  ```

2. In addition/instead, it'd be really helpful for all click, mousedown, on, etc. events to have this built-in to the event.  Whenever the event has clientX and clientY defined, it could be transformed as above and added to the event as transformX and transformY (or svgX and svgY, or similar).  These would be localized to the node object that the event was attached to.

This type of code is already in the extensions svg.draw.js and svg.resize.js, and it seems useful whenever interacting with SVG via the mouse, so it seems natural to add to the base.  But feel free to reinterpret how you think is best!

**Comment by Fuzzyma** [comment]
I will consider to implement point 1. That seems to be a nice to have feature.

Point 2 is not rly possible to implement. svg.js cant change the data an event is giving to you.
And we cant replace every binding from an event with some custom event to add these data only to fire this event then on the element. At least that does not souns clean.

**Comment by edemaine** [comment]
Oh, I assumed that you could add additional attributes to the event object before passing it in the callback.  You're saying that event objects read-only?

**Comment by edemaine** [comment]
Here's an example of what I imagined for Point 2.  Feel free to still disagree / think this is too "hacky".  But it is possible to attach extra attributes to the event before calling the callback.  This is just for callbacks set via the .click, .mousedown, etc. methods (not all events), which is what I meant originally but didn't say very clearly -- sorry for any confusion!

[svg.js.patch.txt](https://github.com/wout/svg.js/files/32563/svg.js.patch.txt)

**Comment by Fuzzyma** [comment]
Thats how it could be done indeed. But as you said this is really hacky. Furthermore we try not to alter native Objects (like the Event Object) by adding properties to it.
Imo the implementaton of Point 1 is enough anyway. You then can calculate your coords on your own as you like.

**Comment by edemaine** [comment]
Sounds good!

**Comment by akauppi** [comment]
Giving my 2c here, due to #437.

I initially thought @edemaine 's 2. to be hackish, as well, but is it? I also thought that it would cause unneeded conversions when no-one's really checking those events. But... if the user does interaction, some code will eventually run the matrix translation code. Therefore, it might just as well be done ready and carried in the event. I might like that.

My own asking - in #437 - is simply that the `SVG.Matrix` of svg.js would be able to do transforms. Currently, it is not. This causes me to need to use the native SVG point creation as well, and it all smells a bit fishy. I like code to be able to stay at one abstraction level.

@edemaine If you are working with UI events and svg.js, you might want to have a look at the svg.rx.js I've been doing. It uses the Reactive Streams abstraction for any user interface events, thus changing the way SVG applications can be structured, quite a bit. Would like to hear your comments.

**Comment by Fuzzyma** [comment]
Any ideas on how to name such a function?
- screenPointToElement
- screenPointToUserSpace
- SOTUS (i know the O has to be a P but hey...)
- pointToElement
- pointToUserSpace

The name with the best description would be `screenPointToUserSpace` but nobody likes such long names.

I am not even sure if UserSpace is entirely correct here because of you transform the point into an svg-element with viewport set, it would be wrong because ctm() gets the current transformation matrix which is not affected from Viewport.

So maybe `screenPointToElement` would be better?

Anyone has a genius idea?

**Comment by akauppi** [comment]
I don't really see the need for a specialized function that important. With it, comes the need for documenting, need for learning, (need for naming, eh!) etc. etc. If `SVG.Matrix` can `.transform` a pair of coordinates to another, we can do without the `.node` reference. My pain point simply is the need to dive deeper than svg.js to do an essential operation.

So @edemaine 's sample would be:

```javascript
function transformPoint(screenX, screenY) {
  return this.screenCTM().inverse().apply( screenX, screenY );
}
```

The `.apply` could also be called `.transform`. It would take either two integers (as above) or `[Int,Int]`, as do other uses of points (e.g. `line.plot`). It would return `[Int,Int]`.

**Comment by Fuzzyma** [comment]
The SVG.Matrix class is written for element transforms in the first place. It delivers methods to scale, rotate and so on.
Adding an `apply` method which handles points would destroy this seperation and lead to confusion.
The code I wrote for the SVG.Point would lead to this:
```javascript
function transformPoint(screenX,screenY) {
  return new SVG.Point(screenX, screenY).transform(this.screenCTM().inverse());
}
```
I think its still managable.
However I just found a simple version of point 1 of the first post which would be this:
```javascript
SVG.extend(SVG.Element, {
  // Transform a point to userspace
  point: function(x, y) {
    return new SVG.Point(x,y).transform(this.screenCTM().inverse());
  }
})
```

This would turn the `transformPoint` function to this:
```javascript
function transformPoint(screenX, screenY) {
  return this.point(screenX, screenY)
}
```

Your thoughts?

**Comment by akauppi** [comment]
Nice. See #437 that I closed for my comments.

**Comment by Fuzzyma** [comment]
would be cool if anyone could test that for his needs :)
