### ISSUE TITLE
image position when used to fill element

### ISSUE THREAD

**Issue by robertmartin** [wout/svg.js#419]
There is no way to position an image when it is used to fill an element.  In the case of a polygon, it would be great to be able to specify the x,y (left,top) coordinate of the image.  A bit of sugar would be the ability to specify the x,y as the center of the image, which would be centered in the element.  Additional sugar would be an attribute that would specify whether the image would tile, stretch, or not within the element.  One use case would be the ability to leverage sprite sheets and display just the portion of the sprite sheet viewable in the element.

**Comment by Fuzzyma** [comment]
There **is** a way - indeed there are multiple ways.

```javascript
var image = draw.image(...) // first create the image
var rect = draw.rect(100,100).fill(image)

image.move(...) // as you like

// or

var image = rect.reference('fill') // returns the image
image.move(...)
```

Please read the documentation before creating an issue.
There will be no sugar for the position because as i said in #420 the pattern is not bound to only one element. Furthermore you can easily do that yourself:

```javascript
var box = rect.bbox()
image.center(bbox.cx, bbox.cy)
```

Thats a two-liner - no sugar needed.

You can achieve stretching by setting the `preserveAspectRatio` attribute on the image. You just have to set the width and height if the elemet to the ones of the element first.

However: The features you request here go far over the amount which should be covered by a lib which serves the most use cases. Feel free to write a plugin for that which is a piece of cake with svg.js

**Comment by robertmartin** [comment]
I read the documentation before creating an issue.  I experienced what I thought was a genuine issue with a POLYGON.  Given your tone and unwillingness to help I have decided to move to a different library.

**Comment by Fuzzyma** [comment]
There is no difference when you choose a polygon instead of a rect. Furtermore I gave you everything to solve your problems: What do you expect?
