### ISSUE TITLE
Exported tspan lacks dx attr

### ISSUE THREAD

**Issue by erivas3649** [wout/svg.js#427]
Exported svg doesn't contain the dx attribute on the tspan's, instead x attribute is set and this causes problems  with plugin draggable as mentioned on issue #369 

In this fiddle (https://jsfiddle.net/3upj7e1o/6/) you can drag the text around, export, and import the previously exported data.

**Comment by joarobles** [comment]
When a tspan is created it shouldn't set the x attribute either, just dx and dy

**Comment by joarobles** [comment]
Commenting lines 3659 and 3660 as follows seem to solve this issue:


        this.lines().each(function() {
          if (this.dom.newLined) {
            //if (!this.textPath)
            //  this.attr('x', self.attr('x'))

            this.attr('dy', self.dom.leading * new SVG.Number(self.attr('font-size')))
          }
        })

**Comment by Fuzzyma** [comment]
Please take a deeper look into the code or read the documentation.
It sais:
>As opposed to html, where leading is defined by line-height, svg does not have a natural leading equivalent. In svg, lines are not defined naturally. They are defined by <tspan> nodes with a dy attribute defining the line height and a x value resetting the line to the x position of the parent text element. But you can also have many nodes in one line defining a different y, dy, x or even dx value.

The x-value of the tspan is importanz to create lines in svg. If you dont want that, use `plain()` or create text using the callback function (https://github.com/wout/svg.js#text).
Its not an issue with the lib but with the plugin.

Your problem with the draggable plugin ins related to #428 because your data is not set properly
