### ISSUE TITLE
Incorrect data attribute for text nodes

### ISSUE THREAD

**Issue by joarobles** [wout/svg.js#428]
Using Chrome 47.0.2526.80 (64-bit) on OS X 10.11.1 exported text nodes would contain a __data__ attribute instead of an __svgjs:data__, this would cause issues when importing an exported svg such as "attribute data redefined in entity".

In this [fiddle](https://jsfiddle.net/3upj7e1o/6/) you can see that the exported text node would look like this, note the __data__ attribute:

```xml
<text id="SvgjsText1012" font-family="Helvetica, Arial, sans-serif" x="150" y="94.203125" data="{&quot;leading&quot;:{&quot;value&quot;:1.3,&quot;unit&quot;:&quot;&quot;}}">
```

This was also tested in Safari 9.0.1 with the same result, could be related to this [reported bug in Webkit](https://bugs.webkit.org/show_bug.cgi?id=140488)

**Comment by joarobles** [comment]
Adding this line after 1212 would solve this issue:

      // remove previously set data
      this.node.removeAttribute('svgjs:data')
      this.node.removeAttribute('data') // <== notice me senpai!

**Comment by Fuzzyma** [comment]
The issue ist not that the data attribute is not removed. Its more the fact that its not set properly.
All Browsers handle that kinda incorrect. We have to convince safari to do the export properly

**Comment by Fuzzyma** [comment]
I cannot reproduce this bug on windows and I have no Mac to test it there...

**Comment by Fuzzyma** [comment]
@snowyplover do you have a Mac where you can reproduce that? I would like to add this fix to the next release before releasing it

**Comment by snowyplover** [comment]
I have a friend's Mac available at the moment, though it is fairly old: MacOS 10.6.8.
It has Chrome 47.0.2526.111

It does reproduce this bug. At the linked fiddle, both the <text> element and the <tspan> element have odd looking data attributes.

The bug also shows up on my machine which runs Ubuntu Studio 14.04, and has Chrome 47.0.2526.106.

**Comment by Fuzzyma** [comment]
mh - ok - thats something could run in a vm.
However: When you replace [this line](https://github.com/wout/svg.js/blob/bf0dd2a1cc6eeca0ec50ffcd38f0e57ab4fb2911/dist/svg.js#L1233) with `setAttribute` instead of `setAttributeNS` - does it solve that problem? (note that setAttribute only has 2 arguments)

**Comment by snowyplover** [comment]
I'm not completely sure what I'm doing here, but all the variations I tried format the data attribute the same way on my machine. (This includes the most obvious variation of just omitting the first argument when changing from `setAttributeNS` to `setAttribute`.)

[Here is the fiddle](https://jsfiddle.net/3upj7e1o/7/) I'm using.

I can try it out on the Mac tomorrow, if that would still be helpful.

Is it actually a problem that the data attribute is formatted using HTML entities? While that's not obviously correct, it's not obviously an error either.

**Comment by Fuzzyma** [comment]
It may related to the mistake you made :D.
Your function was saved in `SVG.Element.writeDataToDom` instead of `SVG.Element.prototype.writeDataToDom`. Updated fiddle: [here](https://jsfiddle.net/3upj7e1o/8/)

In my browser both works `this.node.setAttribute` and `this.node.setAttributeNS`.

I was unsure about the html entities, too. But it seems to work albeit its ugly.
Maybe I will write a JSON.stringify which doenst use doule quotes...

**Comment by snowyplover** [comment]
I could see different effects when I varied the code in the replacement `writeDataToDom`, so what I did appeared to have been functional.

If I am following you correctly, your intent is to point out that I have not replaced the original `writeDataToDom` with the altered one. This is true. And given that was what I was trying to do, it's a useful point. However, as I understand the JS object model and the svg.js machinery, what I have actually done is override the original with the altered one: the object `SVG.Element` is in the prototype hierarchy of all instantiated elements, so instantiated elements will 'see' direct changes to the properties of `SVG.Element` such as the one I made. In other words, the effect should be what I intended, even if the mechanism is different.

I have also just realized that I was looking for the wrong bug. I thought the problem was the HTML entities. I'm not sure _why_ I thought that as the problem is stated pretty clearly above...

Anyway, on my machine: `setAttributeNS` seems to work OK when I run it on the DOM through the (Chrome) console; however, namespaces that appear in the DOM don't necessarily show up in the export string from svg.js. This suggests there might be some issue in the code the library uses to shadow attributes.

On the other hand, the fix you suggested (using `setAttribute`) does solve the problem of getting the namespace to export correctly for the current case.

**Comment by Fuzzyma** [comment]
>I could see different effects when I varied the code in the replacement writeDataToDom, so what I did appeared to have been functional.

I tried this out, too but without the `prototype` keywork it doesnt change anything in my tests.
It would really wonder if it would change something because only the prototyped methods are accessible on the instance. Every method which is not prototyped is just a function on that object and can only called from that object (in your case `SVG.Element.writeDataToDom()`)

Btw - the svg.js-way of doing this would be `SVG.extend(SVG.Elemenet, {/* methods */})`.
However - you said that `setAttribute` works which is great. Sometimes we have to cheat vs the specification to get what we want...

I read somewhere that the `NS` functions are buggy when used in other contect than html (which is maybe the case here because we are in svg)

**Comment by Fuzzyma** [comment]
@snowyplover may you test this again? :)

**Comment by snowyplover** [comment]
On my machine, and running the poster's original fiddle, the `svgjs:data` attributes now have the namespace applied. The value of the attribute for the &lt;text> element has changed from (without entities)

  `{"leading": {"value": "1.3"}}`

to

  `{"leading": "1.3"}`

**Comment by Fuzzyma** [comment]
Yes - thats intended. I changed the JSON representation from SVG.Number (didnt know that is possible before). It is now e.g. `{"leading": "1.3px"}` instead of `{"leading": {"value": "1.3", "unit":"px"}}`
