### ISSUE TITLE
Distribution files for 2.2.5 have incorrect version number

### ISSUE THREAD

**Issue by snowyplover** [wout/svg.js#436]
In version 2.2.5, the headers for both svg.js and svg.min.js list the version as 2.2.4.

package.json and other tracking files have the correct version.

**Comment by Fuzzyma** [comment]
Yes I missed to run the final gulp before committing. Since this will be
fixes with the next commit I didn't change it :)

snowyplover <notifications@github.com> schrieb am Sa., 09.01.2016, 10:52:

**Comment by snowyplover** [comment]
Ah, I figured that must have been what happened.

While mislabeled files won't break user code, they can puzzle a human that pulls up the file (as happened to me), and could perhaps confuse automated versioning code somewhere.

My interpretation of the Semantic Versioning rules is that such mislabeled files count as "backwards incompatible changes" -- which, in a sense, they actually are. The way to deal with this might be to follow the part in the [Semver FAQ](http://semver.org/) concerning "What do I do if I accidentally release a backwards incompatible change as a minor version?" In other words, a new version could be released (just a patch in this case) that only

1. fixes the version number, and
2. adds a comment (to CHANGELOG.md, I guess) warning against using the invalid version

Anyway, that's my proposal. It *is* possible I'm just weird, though... :)

**Comment by Fuzzyma** [comment]
As far as I know a Backwards incompatible change is something which breaks the api which means methods and parameters are changing. This is not the case when just a comment is missplaced :D.
Maybe that is just my interpretation but since all packe manager will pull the right version anyway I didnt spend much time on something like this.
The Version number is generated when gulp is run which i accidentially missed after changing package.json. Its more or less a userinfo - in my opinion not worth a bugfix :P.

**Comment by snowyplover** [comment]
I suppose I am taking "backwards incompatible change" as having the intent of something like "any change that breaks the (admittedly subjective, in part) contract between dev and user". But if all the package managers are happy, I suppose there's nothing to worry about.

In any case, I can certainly understand the choice that this is not worth bothering with.

**Comment by Fuzzyma** [comment]
Next update will be soon so I will close that for now :)
