### ISSUE TITLE
How to apply SVG.Matrix transform?

### ISSUE THREAD

**Issue by akauppi** [wout/svg.js#437]
Hi,

svg.js has the `SVG.Matrix` abstraction but I cannot find a way to apply such a matrix on a coordinate pair. The [line in question](https://github.com/akauppi/svg.rx.js/blob/master/src/svg.rx.js#L75) needs to dive back to `.native()`.

Is there something I am missing here? I'd prefer doing without the SVG native point objects, or by having svg.js provide an abstraction over them. Is anything in this area in the plans?

**Comment by Fuzzyma** [comment]
Do you mean the point which is returned from root.createSVGPoint()? It is
planned to implement a transform point function which transforms a point
with a given matrix. But this is not dome yet.
You can use the native matrix class Anyway. You just have to fall native()
on the matrix before you use it which returns the underlying matrix.

Asko Kauppi <notifications@github.com> schrieb am Sa., 09.01.2016, 20:08:

**Comment by akauppi** [comment]
Hi @Fuzzyma 

Unfortunately the line link had moved, but you got the point :) right. I need the `createSVGPoint` call because `SVG.Matrix` does not provide a transform. 

#403 looks like a solution I could live with. I'm slightly concerned about adding something always to events - but then again any interactions are probably intentional so the matrix translation would get done by some code, eventually, anyways.

I will now mention #403 in my source for reference and close this issue. Thanks for the info.

**Comment by Fuzzyma** [comment]
I just wrote an implementation for the SVG.Point. Albeit its very clean its more or less much code for only one method (`transform`). I dont like that fact but I think it will be neccessary anyway...

**Comment by akauppi** [comment]
Yeah. I think SVG.Point would make sense but it should then be consistently supported throughout, i.e. with things like `line.plot`. All or nothing is a good approach for us developers.

On the `svg.rx.js` side, I'm thinking of also making a Point class. It would be interesting in the way that it could be used to attach SVG elements together. One moves, the other follows. Let's see how far that comes?

**Comment by Fuzzyma** [comment]
The SVGPoint Object is not related to any sort of attribute like in polygons or lines. It is a tool to transform a point into another userspace. I dont think that it would make sense to change the representation of `SVG.PointArray` to hold only SVG.Points because thats not what this points are for.
You can manually path an Array of x,y to the constructor to convert it to an SVG.Point but I wont do it by default!

**Comment by akauppi** [comment]
Thanks for clarifying. I assumed that the native browser SVG support was using SVGPoint also for other things.

**Comment by Fuzzyma** [comment]
I wouldnt be suprised if this would coming. Most documentations for the SVGPoit are not even written (https://developer.mozilla.org/de/docs/Web/API/SVGPoint) or very short (https://msdn.microsoft.com/de-de/library/ff972109%28v=vs.85%29.aspx). Imo because there isnt much to say.
But maybe later they will add something like a PointList to SVGPolygon and SVGPolyline which then would for sure hold SVGPoint`s. But thats just guessing for now^^

**Comment by akauppi** [comment]
I did a bit more experimenting, and the conclusion would be that this (abstracting matrix transformation within svg.js is not worth it). Listing the reasons [here](https://github.com/akauppi/svg.rx.js/blob/master/_Unused_/matrix_apply_snippet.js#L5-L12). (that's not active code - something I placed aside)

The reasons being:

SVGPoint seems like an optimization thing closely connected with the matrix conversion. Handling its lifespan is important, and a modularized ("just apply this matrix please") is not able to work without creating an SVGPoint. 

If the `SVG.Matrix` has access to the `SVG.Doc` it's in, this changes somewhat. But then, would it be safe to keep just one buffer for all drag events happening, even simultaneously? I'm not liking to go there. My current code creates a buffer per drag, and works well. Also, the end users don't know about `.node` and `.native` so I consider the case closed.

**Comment by Fuzzyma** [comment]
Sorry to slow down you here - 	It's all Greek to me :D.
You are right when you say, that the SVGPoint is closely connected to the SVGMatrix. This is not true the other way round because matrix is used for several other usescases.

Anyway I didnt think I got your point. Is my solution good for you or is it not? :D

**Comment by akauppi** [comment]
@Fuzzyma: thanks for this discussion. I think I will yield any suggestions from my side, for now, for two reasons.

1. When I opened this issue, I assumed the omission of the ability to apply transforms within svg.js realm was unintentional. That a small fix would do. It seems it's more complicated than that.

2. Whatever the `svg.rx.js` code uses internally, for coordinate transformation, is simply an implementation detail. One `.node` and `.native` in there don't really hurt.

So it kind of becomes a no-issue, for me, and I'll look at other things. I am glad I got this sorted and I am indeed very pleased with svg.js at large - maybe failed to say this! My actual project was started using SnapSvg but I find your project better documented and easier to understand, all along. So let's keep in touch when needed - both ways.
