### ISSUE TITLE
Simultaneously animation on single object

### ISSUE THREAD

**Issue by sharonlin** [wout/svg.js#452]
I've upgraded the svg.js to latest from 1.01 and currently the following code stop working.

g.animate(1000).move(0, 0).opacity(0).scale(0).skew(50).
in previous version of svg.js the animation played in parallel.
After upgrading to latest version seems like the last animation is the only one that work.

Any idea what is the problem?
Thanks,
Sharon

**Comment by mkorganashvili** [comment]
I have the same problem

**Comment by emilyhorsman** [comment]
:+1:  Also having this issue,

```
g.stop().animate(750).rotate(-720).move(-191, 0)
```

Calling `.animate(750).rotate(-720)` and `.animate(750).move(-191, 0)` works individually, but not in a chain. No errors thrown in the console.

**Comment by Fuzzyma** [comment]
How it comes that everyone has this problem at the same time?
Does this problem only occurs when using groups?

**Comment by sharonlin** [comment]
Anyone overcome this problem?

**Comment by mkorganashvili** [comment]
@Fuzzyma  yes, it occurs only when using groups.

**Comment by Fuzzyma** [comment]
The current master branch should fix this problem to a certain degree. However you should use relative transformations instead of the move command when dealing with groups. 
Absolute transformations are sometimes an impossible thing. 
(note that the move command from a group just maps to a translation)
