### ISSUE TITLE
Status of SVG.js Plugins using SVG.js 2.0?

### ISSUE THREAD

**Issue by villanus** [wout/svg.js#457]
There are a good set of SVG.js plugins but the page reads:
"** Caution: Not tested for SVG.js 2.0 **"
http://documentup.com/wout/svg.js#plugins

Most of these plugins have not been updated for 2+ years. 
Is there a way to get an update on which of the plugins are going to be supported officially by 2.0?

For each plugin it would be nice to know:
a. Works with 2.0
b. Not required in 2.0 (part of svg.js)
c. Does not work with 2.0 - Not Planned
d. Does not work with 2.0 - Planned 

The ones I am most interested in are:
- Absorb - https://github.com/wout/svg.absorb.js
- Draggable - https://github.com/wout/svg.draggable.js
- Export - https://github.com/wout/svg.export.js
- Import + Parser - https://github.com/wout/svg.import.js
- SVG Resize - https://github.com/fuzzyma/svg.resize.js
- SVG Select - https://github.com/fuzzyma/svg.select.js

**Comment by Fuzzyma** [comment]
I will just answer your list for now until I find some time to complete this:

- Absorb - obsolete (b)
- Draggable - works (a)
- Export - obsolete (b)
- Import - obsolete (b)
- SVG Resize - works (a)
- SVG Select - works (a)

For all other non-obsolete plugins applies, that the support is planned. Most of them should work regardless of the version because the api did not changed THAT much. Anyway - PRs are very welcome!

**Comment by villanus** [comment]
Thanks!!!

**Comment by wout** [comment]
@Fuzzyma 
Shall I just delete all obsolete repos?

**Comment by Fuzzyma** [comment]
They are still in use from poeple who use svg.js v1 so please no :D

**Comment by wout** [comment]
OK, I didn't realise that was the case. :)
Then I'll announce them as incompatible/obsolete for the latest version where required.
