### ISSUE TITLE
Version 2.x much slower than 1.x

### ISSUE THREAD

**Issue by DetsCastelli** [wout/svg.js#469]
After having performance issues in my application, which draws some dozen lines every second, I found out, that using svg.js V1.0.1 is much faster than V 2.2.0 without changing my code: where V 2.2.0 needs approx. 1.400ms to draw, V 1.0.1 does the same in about 300ms!
Will this be fixed or should I keep using V 1.0.1?

thx in advance, Dets ...

**Comment by ibrierley** [comment]
Would be useful to include the code you are using to test.

**Comment by DetsCastelli** [comment]
I've prepared some code:

[Grünbandgrafik.htm.txt](https://github.com/wout/svg.js/files/195198/Grunbandgrafik.htm.txt)
[gruenband.js.txt](https://github.com/wout/svg.js/files/195199/gruenband.js.txt)

Rename *.htm.txt to .htm and *.js.txt to .js

When you scroll with your mouse wheel, the graphic get resized. In the javascript console the time in ms used for drawing is printed. With svj.js v 1.0.1 the drawing takes about 150ms on my machine, with v 2.2.5 it takes ~ 400ms

**Comment by wout** [comment]
I am on MacBook with an Intel Core M 1.2 and am experiencing a similar performance hit.
About 100ms on v1.1.0 and 200ms on v2.3.0.

Be aware though that SVG.js v1 is very different from v2.
With v2 we introduced the ability to adopt existing inline SVG's.

Internal representations are therefore removed/avoided and this adds to the overall performance hit.
Nevertheless, we'll have a closer look to see where we can gain back some of the original speed.

**Comment by ttsirkia** [comment]
Is there any progress with this issue? Is it likely that there will be a performance boost in v2 in the future?

**Comment by wout** [comment]
Yes, we're working on it. Could you point out where you are experiencing the biggest performance hit?

**Comment by ttsirkia** [comment]
I haven't used the library yet. I have a project done with Snap.svg and it is a bit slow. I'm currently searching another library to boost the existing code. Svg.js might be a good choiche but then I just noticed this issue. One option would be to use version 1.x as nothing very fancy is required.

**Comment by ibrierley** [comment]
Don't want to derail this thread, but if you post a Snap git issue, I'd take a quick look as I'm quite interested in performance of svg. Might be some crossover with other libs in general.

**Comment by wout** [comment]
@ttsirkia Generally SVG.js is faster than Snap although v2.x.x is performing less than v1.x.x. that's because we removed internal references in v2 to be able to adopt existing SVG documents, rather than build them from scratch. If you don't need to work with existing SVG's, you might consider using v1 but be aware that v2 also introduced breaking changes so moving from v1 to v2 afterwards might be a pain. And since we're no longer supporting v1 that might become an issue.

**Comment by ttsirkia** [comment]
@wout Thanks for the info! I think I'll do some experiments what is the performance difference between Snap.svg and Svg.js to see if it worthwhile to change the existing implementation and also check the difference between Svg.js versions 1 and 2. If I get some interesting results, I can post a comparison of these three options.

**Comment by wout** [comment]
Great, I'm curious to see the results.  In the meantime we bumped to version 2.3.4 which brings a lot of speed when it comes to creating elements.

**Comment by wout** [comment]
As a tool for us but also for our users, we added a tiny benchmarking system.
It can be found in the bench directory of the project.

You can use it to quickly test the performance of SVG.js vs native and vs Snap.svg.
Here is a quick test comparing three scenarios against the three setups:

![screen shot 2016-08-04 at 21 15 48](https://cloud.githubusercontent.com/assets/107324/17415305/95f809a6-5a89-11e6-90d5-329d4ff428fd.png)

In this particular test, SVG.js is more than 6 times faster than Snap.
Your numbers will probably be even better because I am on an Intel Core M machine.

**Comment by ttsirkia** [comment]
Very interesting and promising result!

**Comment by wout** [comment]
Glad we could be of help. This tool also allows us to point out weak performance of SVG.js. If you find something where we're lacking, please post the results so we can fix those issues asap.

**Comment by wout** [comment]
The speed issue seems to be resolved. Please let us know if you have any more questions.
