### ISSUE TITLE
Migration from 0.32 to 2.3.0

### ISSUE THREAD

**Issue by sunteam** [wout/svg.js#479]
**Hi guys,**
I want to migrate from 0.32 to 2.3.0. Is that painful? Is there any documenation about it?

Best Regards
Piotr

**Comment by Fuzzyma** [comment]
Wow - that's a huge step! 
No documentation - sorry. Just try it and fix the errors :)

**Comment by wout** [comment]
Hi,
The biggest difference between v1 (and below) and v2 are internal representations and references.
In v2 both of them are removed in order to be able to work with existing inline SVG's.

Where you would have `this.parent` as a static variable on an element, you now have `this.parent()` as a method.
This it the case with all static references.

**Comment by sunteam** [comment]
Thanks a lot for the explanation.

**Comment by wout** [comment]
No prob, let us know if you have more questions.
I would just go for it, shouldn't be that hard.
